### ISSUE TITLE
Uncaught TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by yahyaKacem** [ka-ka-xyz/atom-charcode#3]
Steps to reproduce below any left click in the editor window.

**Atom Version**: 0.188.0
**System**: linux 3.16.0-33-generic
**Thrown From**: [atom-charcode](https://github.com/ka-ka-xyz/atom-charcode) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'status' of undefined

```
At /home/yahya/.atom/packages/atom-charcode/lib/atom-charcode.coffee:93

TypeError: Cannot read property 'status' of undefined
  at /home/yahya/.atom/packages/atom-charcode/lib/atom-charcode.coffee:94:41
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app/src/cursor.js:61:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/usr/share/atom/resources/app/src/marker.js:301:22)
  at /usr/share/atom/resources/app/src/marker.js:56:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.update (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:569:22)
  at Marker.module.exports.Marker.setRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:189:19)
  at Marker.module.exports.Marker.setBufferRange (/usr/share/atom/resources/app/src/marker.js:172:32)
  at /usr/share/atom/resources/app/src/selection.js:131:24
  at Selection.module.exports.Selection.modifySelection (/usr/share/atom/resources/app/src/selection.js:902:7)
  at Selection.module.exports.Selection.setBufferRange (/usr/share/atom/resources/app/src/selection.js:121:19)
  at /usr/share/atom/resources/app/src/text-editor.js:1797:29
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:2125:43)
  at TextEditor.module.exports.TextEditor.setSelectedBufferRanges (/usr/share/atom/resources/app/src/text-editor.js:1790:19)
  at TextEditor.module.exports.TextEditor.setSelectedBufferRange (/usr/share/atom/resources/app/src/text-editor.js:1773:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onGutterClick (/usr/share/atom/resources/app/src/text-editor-component.js:567:19)
  at TextEditorComponent.onGutterClick (/usr/share/atom/resources/app/src/text-editor-component.js:3:61)
  at TextEditorComponent.module.exports.TextEditorComponent.onGutterMouseDown (/usr/share/atom/resources/app/src/text-editor-component.js:559:21)
  at GutterComponent.<anonymous> (/usr/share/atom/resources/app/src/text-editor-component.js:3:61)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/src/gutter-component.js:3:61)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-monokai"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "project-switcher"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
angularjs, v0.2.0
angularjs-styleguide-snippets, v0.6.0
atom-alignment, v0.12.0
atom-angularjs, v0.1.2
atom-charcode, v0.3.0
atom-color-highlight, v3.0.8
atom-monokai, v0.6.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.7.1
autocomplete-plus-async, v0.22.0
editor-stats, v0.17.0
editorconfig, v0.3.3
emmet, v2.3.4
figlet, v0.3.1
git-diff-details, v0.8.0
git-go, v1.0.0
git-log, v0.3.0
git-projects, v1.12.0
gulp-snippets, v0.6.1
highlight-line, v0.10.1
highlight-selected, v0.9.1
javascript-snippets, v1.0.0
jslint, v1.2.1
language-javascript-jsx, v0.3.1
less-autocompile, v1.0.0
linter, v0.12.0
linter-htmlhint, v0.0.10
linter-less, v0.3.1
minimap, v4.7.1
minimap-color-highlight, v4.1.0
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
omni-ruler, v0.3.1
open-last-project, v0.3.5
project-manager, v1.15.5
project-palette-finder, v2.4.16
selection-count, v1.6.3
selection-outlines, v0.2.0
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by ka-ka-xyz** [comment]
Sorry for lazy response.
I believe bfb29032b6d67c7f08f1cfc408f53dd7309ed32f would fix it.
